"""Generate the two promised handoff tables (items 4 and 5).

`REBUTTAL_HANDOFF.md` has carried "script-generated … lands at the
pre-submission final pass" for `tab_lambda_shuffle_tsweep.md` and
`tab_dq_tsweep.md` since the overnight pass. This is that script.

Both tables are built from committed result JSONs, so they regenerate
deterministically and carry their own source list. Metric is
`lambda_recovery_v2` (the ridge v2 probe) with its untrained twin, which
is the pairing both figures plot.

    .venv/bin/python scripts/gen_handoff_tables.py
"""
from __future__ import annotations

import json
import statistics as st
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HUNT = ROOT / "experiments/explorations/task_hunt"
OUT = ROOT / "figs_writeup"
METRIC = "lambda_recovery_v2"


def load(p: Path):
    with p.open() as f:
        return json.load(f)


def by_T(records, kind: str) -> dict[int, list[float]]:
    """{T: [metric per seed]} for one twin kind, dropping absent metrics."""
    out: dict[int, list[float]] = {}
    for r in records:
        if r.get("kind") != kind or not r.get("ok", True):
            continue
        v = (r.get("metrics") or {}).get(METRIC)
        if v is None:
            continue
        out.setdefault(int(r["T"]), []).append(float(v))
    return out


def cell(vals: list[float]) -> str:
    if not vals:
        return "—"
    if len(vals) == 1:
        return f"{vals[0]:.4f} (n=1)"
    return f"{st.mean(vals):.4f} ± {st.stdev(vals):.4f}"


def twin_table(trained, untrained, sources: list[str], title: str, notes: str) -> str:
    Ts = sorted(set(trained) | set(untrained))
    lines = [
        f"# {title}",
        "",
        "Script-generated by `scripts/gen_handoff_tables.py` — regenerate",
        "rather than hand-edit. Metric: `lambda_recovery_v2` (ridge v2",
        "probe), mean ± sd across seeds.",
        "",
        "| T | n seeds | trained | untrained twin | trained − twin |",
        "|---|---|---|---|---|",
    ]
    for T in Ts:
        tr, un = trained.get(T, []), untrained.get(T, [])
        delta = (
            f"**{st.mean(tr) - st.mean(un):+.4f}**" if tr and un else "—"
        )
        lines.append(f"| {T} | {max(len(tr), len(un))} | {cell(tr)} | {cell(un)} | {delta} |")
    lines += ["", notes, "", "**Sources:**"]
    lines += [f"- `{s}`" for s in sources]
    return "\n".join(lines) + "\n"


def main() -> None:
    # ── item 4: λ̂ backtracking-intensity, shuffle overlay ────────────
    # This one is an ORDERED-vs-SHUFFLED overlay, not a trained/untrained
    # twin: the summary is keyed "arch/T" with ordered/shuf means already
    # aggregated over seeds, and the T6/T10 fill arrives per-cell.
    lam_dir = HUNT / "lambda_intensity/results"
    ov = load(lam_dir / "shuffle_overlay.json")
    rows: list[tuple[str, int, int, float, float, float, float, float]] = []
    for key, s in ov.get("summary", {}).items():
        arch, t = key.rsplit("/T", 1)
        rows.append((arch, int(t), s["n"], s["ordered_mean"], s["ordered_sd"],
                     s["shuf_mean"], s["shuf_sd"], s["gap_mean"]))
    # fold the T6/T10 fill in from its per-cell file
    fill: dict[tuple[str, int], list[tuple[float, float]]] = {}
    for r in load(lam_dir / "t6t10_overlay.json"):
        fill.setdefault((r["arch"], int(r["T"])), []).append(
            (float(r["canonical_r"]), float(r["r_shuf"])))
    for (arch, t), pairs in fill.items():
        o = [p[0] for p in pairs]
        sh = [p[1] for p in pairs]
        rows.append((arch, t, len(pairs), st.mean(o),
                     st.stdev(o) if len(o) > 1 else 0.0, st.mean(sh),
                     st.stdev(sh) if len(sh) > 1 else 0.0,
                     st.mean(o) - st.mean(sh)))
    rows.sort(key=lambda r: (r[0] != "txc_batchtopk_post", r[0], r[1]))

    lines = [
        "# λ̂ backtracking-intensity — shuffle overlay T-sweep",
        "",
        "Script-generated by `scripts/gen_handoff_tables.py` — regenerate",
        "rather than hand-edit. Metric: `lambda_recovery` (canonical r),",
        "mean ± sd across seeds. **Gap = ordered − shuffled.**",
        "",
        f"Anchor gate: **{'ALL PASS' if ov.get('anchor_gate_all_pass') else 'CHECK'}**"
        f" · overlay status: *{ov.get('status')}*",
        "",
        "| arch | T | n | ordered | shuffled | gap |",
        "|---|---|---|---|---|---|",
    ]
    for arch, t, n, om, osd, sm, ssd, gap in rows:
        lines.append(
            f"| `{arch}` | {t} | {n} | {om:.4f} ± {osd:.4f} "
            f"| {sm:.4f} ± {ssd:.4f} | **{gap:+.4f}** |")
    lines += [
        "",
        "**T1 rows are the per-token anchors** (`batchtopk_sae`, `tsae`): at "
        "T=1 a within-window shuffle is the identity, so their gap is "
        "exactly 0.0000 by construction — that is the instrument's own "
        "null, not a result.",
        "",
        "**Caveats travel with the figure** (`fig_lambda_shuffle_tsweep`): "
        "T6 dips below T4; T10 is seed-fragile — a venue-localized training "
        "instability, since the same seed/T trains fine on dq. Substrate "
        "`ward_real_lambda_base_l12` (R1-Distill-8B L12), hunt width "
        "d_sae 2048.",
        "",
        "**Sources:**",
        "- `experiments/explorations/task_hunt/lambda_intensity/results/shuffle_overlay.json`",
        "- `experiments/explorations/task_hunt/lambda_intensity/results/t6t10_overlay.json`",
        "- `experiments/explorations/task_hunt/lambda_intensity/SHUFFLE_OVERLAY_CARD.md`",
    ]
    (OUT / "tab_lambda_shuffle_tsweep.md").write_text("\n".join(lines) + "\n")

    # ── item 5: dq question-marks, T-scaling ─────────────────────────
    dq = load(HUNT / "diafaces/results/stage2_dial_real_dqgap_llama31_8b_l14.json")
    dq += load(HUNT / "diafaces/results/dq_t6t10_fill.json")
    dq_tbl = twin_table(
        by_T(dq, "trained"),
        by_T(dq, "untrained"),
        ["experiments/explorations/task_hunt/diafaces/results/"
         "stage2_dial_real_dqgap_llama31_8b_l14.json",
         "experiments/explorations/task_hunt/diafaces/results/"
         "dq_t6t10_fill.json",
         "experiments/explorations/task_hunt/diafaces/DQ_T_FILL_CARD.md"],
        "dq question-marks — T-scaling",
        "**⚑ TOY-class per Dmitry's bar (meeting 07-27): within-SAE use "
        "only.** Shuffle columns are SCREEN-class (overlay ruled out, LOG "
        "00:05); the passed-then-demoted framing travels with this table. "
        "Substrate `dial_real_dqgap_llama31_8b_l14`, hunt width d_sae 2048.",
    )
    (OUT / "tab_dq_tsweep.md").write_text(dq_tbl)

    for name in ("tab_lambda_shuffle_tsweep.md", "tab_dq_tsweep.md"):
        p = OUT / name
        print(f"wrote {p.relative_to(ROOT)} ({len(p.read_text().splitlines())} lines)")


if __name__ == "__main__":
    main()
