"""Generate `figs_writeup/tab_sycgen_budget_matched.md` — the item-6 deliverable.

Han: *"we need to get the budget matched comparison TABLE DONE ASAP."*
This is that table. Script-generated from `sycgen/results/frontier.json`
so it regenerates deterministically; do not hand-edit.

Encodes the binding reporting rules from the pre-registration (LOG
`aa0272633`, amended `567d6818e`) and the hub cross-check (`6a75ddc7b`):

  - budget axis is MEASURED `realized_l0_per_window`. NEVER the derived
    per-token axis, which is `l0_per_window / T` and manufactures a
    "recovery up as budget falls" free lunch (mac-c `c1a9f98ad`).
  - `l0_unit` differs BY ARM: TXC and pooled count nonzeros in a d_sae
    code; stacked sums over T*d_sae slots. Printed, never merged.
  - stacked gets T x the probe input, so a stacked result is partly
    probe capacity. Reported, never netted out — and at T>=8 it is
    UNINFORMATIVE (32768 features vs 1024 windows is underdetermined).
  - three states, not two: above / below / INDISTINGUISHABLE at n=3.
  - the frontier SHAPE is reported, not just the verdict.

    .venv/bin/python scripts/gen_sycgen_budget_table.py
"""
from __future__ import annotations

import json
from pathlib import Path
from statistics import mean, pstdev

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "experiments/explorations/task_hunt/sycgen/results/frontier.json"
OUT = ROOT / "figs_writeup/tab_sycgen_budget_matched.md"


def agg(rows, arm, T, k):
    rs = [r for r in rows if r["arm"] == arm and r["T"] == T
          and r.get("k_tok") == k]
    if not rs:
        return None
    v = [r["recovery"] for r in rs]
    return {"r": mean(v), "sd": pstdev(v) if len(v) > 1 else 0.0,
            "l0": mean(r["realized_l0_per_window"] for r in rs), "n": len(v),
            "unit": rs[0].get("l0_unit", "?")}


def verdict(txc, c):
    """Three states. Crude by design; NOT a significance test (n=3)."""
    d = txc["r"] - c["r"]
    spread = max(txc["sd"], c["sd"])
    if abs(d) <= spread:
        return "INDISTINGUISHABLE", d, spread
    return ("TXC above" if d > 0 else "TXC below"), d, spread


def main() -> None:
    rows = json.loads(SRC.read_text())
    Ts = sorted({r["T"] for r in rows})
    ks = sorted({r["k_tok"] for r in rows if r.get("k_tok") is not None})

    L = [
        "# Item 6 (sycgen) — TXC vs pooled-SAE vs stacked-SAE, "
        "recovery-vs-budget frontier",
        "",
        "Script-generated by `scripts/gen_sycgen_budget_table.py` — "
        "regenerate rather than hand-edit.",
        "",
        "**Why this table exists.** The original item-6 claim compared a "
        "*windowed* TXC against a *per-token* SAE, which establishes "
        "nothing about the architecture. Dmitry's agent ran the missing "
        "baselines and TXC lost. This is that comparison done properly: "
        "**k swept on both SAE arms, compared as frontiers at measured "
        "budget**, because a single \"matched point\" does not exist — "
        "matching per-window necessarily unmatches per-token.",
        "",
        "**Budget axis: measured `realized_l0_per_window`.** The "
        "per-token axis is *derived* (`l0_per_window / T`) and produces a "
        "spurious \"more recovery for less budget\" trend — never use it.",
        "",
        "## Verdict",
        "",
        "| T | TXC r | TXC l0/win | pooled (best @ budget) | verdict vs pooled | stacked | verdict vs stacked |",
        "|---|---|---|---|---|---|---|",
    ]

    tally = {"above": 0, "below": 0, "indist": 0}
    shape = []
    for T in Ts:
        txc = agg(rows, "txc", T, None)
        if not txc:
            continue
        cells = []
        for arm in ("pooled", "stacked"):
            pts = [(k, agg(rows, arm, T, k)) for k in ks]
            pts = [(k, c) for k, c in pts if c]
            elig = [(k, c) for k, c in pts if c["l0"] <= txc["l0"] + 1e-9]
            if elig:
                k, c = max(elig, key=lambda kc: kc[1]["r"])
                state, d, sp = verdict(txc, c)
                note = ""
            else:
                k, c = min(pts, key=lambda kc: kc[1]["l0"])
                if c["l0"] > txc["l0"] and txc["r"] > c["r"]:
                    state, d, sp = "TXC above", txc["r"] - c["r"], max(txc["sd"], c["sd"])
                    note = f" (cheapest costs {c['l0']/txc['l0']:.2f}× TXC — TXC wins **and is cheaper**)"
                else:
                    state, d, sp = "NOT COMPARABLE", 0.0, 0.0
                    note = ""
            key = ("above" if state == "TXC above" else
                   "below" if state == "TXC below" else
                   "indist" if state == "INDISTINGUISHABLE" else None)
            if key and arm == "pooled":
                tally[key] += 1
            cells.append((f"k={k} r={c['r']:.4f} @ {c['l0']:.2f}",
                          f"**{state}**{note}" if not note else f"**{state}**{note}"))
        L.append(f"| {T} | {txc['r']:.4f} ± {txc['sd']:.4f} | {txc['l0']:.2f} "
                 f"| {cells[0][0]} | {cells[0][1]} | {cells[1][0]} | {cells[1][1]} |")

        # frontier shape: pooled's ceiling across ALL k, regardless of budget
        pp = [(k, agg(rows, "pooled", T, k)) for k in ks]
        pp = [(k, c) for k, c in pp if c]
        bk, bc = max(pp, key=lambda kc: kc[1]["r"])
        shape.append((T, txc, bk, bc))

    L += [
        "",
        f"**vs pooled — the honest comparison: above {tally['above']}/{len(Ts)}, "
        f"indistinguishable {tally['indist']}/{len(Ts)}, below {tally['below']}/{len(Ts)}.**",
        "",
        "## The frontier shape — reported because the verdict alone would hide it",
        "",
        "Pooled's **ceiling at any swept budget**, ignoring the budget cap:",
        "",
        "| T | TXC r @ l0/win | pooled BEST r @ l0/win (any k) | pooled budget | does pooled ever reach TXC? |",
        "|---|---|---|---|---|",
    ]
    for T, txc, bk, bc in shape:
        reach = "**no**" if bc["r"] < txc["r"] else "yes"
        # express as a MULTIPLIER and an explicit "more than", not "X% of":
        # a bare "+127%" for a 1.27x ratio overstates by 100 points.
        mult = bc["l0"] / txc["l0"]
        L.append(f"| {T} | {txc['r']:.4f} @ {txc['l0']:.2f} | {bc['r']:.4f} @ "
                 f"{bc['l0']:.2f} (k={bk}) | {mult:.2f}× TXC "
                 f"(+{100*(mult-1):.0f}% more) | {reach} |")

    L += [
        "",
        "**Pooled saturates** — its recovery goes flat across the upper k "
        "range, so beyond a point more budget buys it nothing. That is why "
        "the result is not an artifact of the budget cutoff.",
        "",
        "## Caveats that travel with every number here",
        "",
        "- **n = 3 seeds.** The verdict threshold (`|Δ| ≤ max(sd)`) is "
        "**crude by design and is NOT a significance test** — n=3 does not "
        "support one. `INDISTINGUISHABLE` is a real third state, distinct "
        "from a loss.",
        "- **T=2 is thin** (Δ/spread ≈ 1.16): a slightly different, equally "
        "defensible threshold would move it to indistinguishable. Flagged "
        "*before* the data landed.",
        "- **⚑ Stacked is UNINFORMATIVE at T ≥ 8** and its column should not "
        "be counted: `T·d_sae = 32768` features against `N_WINDOWS = 1024` "
        "is underdetermined, so its collapse is **probe-capacity "
        "overfitting, not architecture**. The honest comparison is TXC vs "
        "**pooled**.",
        "- **Training variance dominates sampling variance** — a "
        "sampling-only σ on a single-seed cell understates by ~1.8–4× "
        "(measured on a *different* leg; it argues underpowering is live, "
        "it does not size it here).",
        "- **Scope:** one task, one substrate "
        "(`sycgen_real_age_llama31_8b_l14`), one layer, d_sae 2048.",
        "",
        "## Provenance",
        "",
        "- Cells: tag `sycgen_keep_r1_rebuilt`, trained on a **rebuilt** "
        "activation cache — **not** pod-D's originals (which survive on HF "
        "and back the *published* exhibit).",
        "- **The rebuilt cache is verified**: retrained SAE anchors "
        "reproduced the recorded values to 3 dp under a closed-form OLS "
        "probe, where exact agreement is essentially impossible unless the "
        "substrate matches.",
        "- Source: "
        "`experiments/explorations/task_hunt/sycgen/results/frontier.json` "
        f"({len(rows)} rows).",
        "- Verdict cross-checked by two independent implementations "
        "(`sycgen/report_frontier.py`, `scripts/verify_frontier_verdict.py`); "
        "they disagreed at T=16 and the disagreement is recorded in the LOG.",
        "",
        "**PTR — pending team ratification.**",
    ]
    OUT.write_text("\n".join(L) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(L)} lines)")
    print(f"vs pooled: above {tally['above']}, indist {tally['indist']}, below {tally['below']}")


if __name__ == "__main__":
    main()
