#!/usr/bin/env bash
# Poll the C7 leaderboard + every cell's probe log every 5 minutes;
# on any change, re-render the paper bundle (markdown + plots) and
# push to origin/final-aniket.
#
# Outputs land in /workspace/aniket/temp_xc_paper (the final-aniket
# worktree) at purified/docs/components/c7_paper_results.md and
# purified/docs/components/c7_paper_assets/.
#
# Usage:
#   set -a; source /workspace/aniket/temp_xc/.env; set +a
#   cd /workspace/aniket/temp_xc-final/purified
#   nohup bash scripts/c7_paper_loop.sh \
#       > logs/c7_paper_loop.log 2>&1 &

set -u

SOURCE_PURIFIED=/workspace/aniket/temp_xc-final/purified
PAPER_WT=/workspace/aniket/temp_xc_paper
PAPER_PURIFIED="$PAPER_WT/purified"
OUTPUT_DIR="$PAPER_PURIFIED/docs/components"
LB="$SOURCE_PURIFIED/results/leaderboard.jsonl"
PROBE_GLOB="$SOURCE_PURIFIED/checkpoints/*/snapshots/eval_log.jsonl"
GH_TOKEN=${GH_TOKEN:-}

cd "$SOURCE_PURIFIED"
log() { printf "[%s] %s\n" "$(date -u +%H:%M:%S)" "$*"; }

# Composite signature of all input files. Re-render when any file changes.
sig() {
    {
        [ -f "$LB" ] && md5sum "$LB"
        for f in $PROBE_GLOB; do
            [ -f "$f" ] && md5sum "$f"
        done
    } 2>/dev/null | md5sum | awk '{print $1}'
}

push_paper() {
    cd "$PAPER_WT"
    # Stage everything under docs/components/ that's relevant to c7 paper.
    git add purified/docs/components/c7_paper_results.md \
            purified/docs/components/c7_paper_assets 2>/dev/null
    if git diff --cached --quiet; then
        log "no diff to commit"
        cd "$SOURCE_PURIFIED"
        return 0
    fi
    local n_cells
    n_cells=$(.venv/bin/python -c "
import json
n = sum(1 for l in open('$LB') if l.strip() and json.loads(l).get('component')=='c7') if __import__('os').path.exists('$LB') else 0
print(n)
" 2>/dev/null || echo "?")
    local commit_msg
    commit_msg="c7 paper auto: refresh bundle ($n_cells leaderboard rows)

Auto-generated by purified/scripts/c7_paper_renderer.py.
Inputs: results/leaderboard.jsonl filtered to component=c7 + every
cell's snapshots/eval_log.jsonl probe stream.

Co-Authored-By: Claude Opus 4.7 (1M context) <noreply@anthropic.com>"
    git -c user.email="aniketdeshh@gmail.com" -c user.name="aniket" \
        commit -m "$commit_msg" >/dev/null
    log "committed $(git rev-parse --short HEAD) — pushing"
    if [ -n "$GH_TOKEN" ]; then
        GIT_TERMINAL_PROMPT=0 \
        git -c "credential.helper=!f() { echo username=x-access-token; echo password=$GH_TOKEN; }; f" \
            push origin final-aniket 2>&1 | tail -3
    else
        log "WARNING: GH_TOKEN unset — local commit only"
    fi
    cd "$SOURCE_PURIFIED"
}

last_sig=""
log "loop started — polling every 300s"

while true; do
    cur=$(sig)
    if [ -n "$cur" ] && [ "$cur" != "$last_sig" ]; then
        log "input signature changed → render"
        if .venv/bin/python -m scripts.c7_paper_renderer \
                --output-dir "$OUTPUT_DIR" 2>&1 | sed 's/^/  /'; then
            push_paper
            last_sig=$cur
        else
            log "renderer FAILED — will retry next tick"
        fi
    fi
    sleep 300
done
