"""Emit auto-generated LaTeX snippets for the C7 paper section, so the
hand-written .tex can ``\\input`` the snippets and stay in sync with
the leaderboard without manual edits.

Outputs:

  - ``c7_pr_auc_table.tex``     — body of the PR-AUC + ROC-AUC table
                                   (columns at S ∈ {1, 2, 4, 8, 16, 32}).
  - ``c7_headline_table.tex``   — body of the inducement headline table
                                   (gc_at_peak, gc_at_baseline, Δgc_peak,
                                   peak_mag, PR-AUC@8, ROC-AUC@8).
  - ``c7_results_macros.tex``   — \\newcommand declarations for the
                                   numbers that the Results paragraph
                                   in main.tex inlines (best-cell name,
                                   peak Δgc value, etc.).

These are *content-only*; the surrounding ``\\begin{table}`` /
``\\caption`` / ``\\label`` lives in the hand-written tex and
``\\input``s the table body.

Usage::

    .venv/bin/python -m scripts.c7_tex_snippets \\
        --output-dir figs/<component>
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

from temp_bench.config import checkpoint_dir, purified_root

PURIFIED = purified_root()
LEADERBOARD = PURIFIED / "results" / "leaderboard.jsonl"
S_GRID = (1, 2, 4, 8, 16, 32)

ARCH_LABEL = {
    "topk_sae":   "TopK SAE",
    "stacked_sae": "Stacked SAE",
    "tsae_paper": "T-SAE",
    "tfa":        "TFA",
    "mlc":        "MLC",
    "txc_base":   "TXC-base",
    "txc_pro":    "TXC-pro",
}

# Display order for headline tables — keep TXC cells together at the bottom
# for visual emphasis, baselines on top.
ARCH_ORDER = ["topk_sae", "tsae_paper", "tfa", "mlc", "stacked_sae",
              "txc_base", "txc_pro"]


def _train_cfg(row: dict) -> dict:
    cfg_path = checkpoint_dir(row["train_key"]) / "config.json"
    if not cfg_path.exists():
        return {}
    return json.loads(cfg_path.read_text()).get("training_cfg", {})


def _bs(row: dict) -> int | None:
    bs = _train_cfg(row).get("batch_size")
    return int(bs) if bs is not None else None


def _is_canonical(row: dict) -> bool:
    if row.get("component") != "c7":
        return False
    if row.get("eval_cfg", {}).get("_extended_mags"):
        return False
    return _train_cfg(row).get("n_steps") == 300_000


def load_canonical() -> list[dict]:
    if not LEADERBOARD.exists():
        return []
    rows = []
    for line in LEADERBOARD.read_text().splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            r = json.loads(line)
        except json.JSONDecodeError:
            continue
        if _is_canonical(r):
            rows.append(r)
    # Dedup: keep latest eval per (arch, train_key).
    by_cell: dict[tuple, dict] = {}
    for r in rows:
        key = (r["arch"], r["train_key"])
        if key not in by_cell or r["ts"] > by_cell[key]["ts"]:
            by_cell[key] = r
    return list(by_cell.values())


def _fmt(v, prec: int = 3) -> str:
    if v is None:
        return r"\texttt{[TBD]}"
    if isinstance(v, float):
        return f"{v:.{prec}f}"
    return str(v)


def _row_label(r: dict) -> str:
    name = ARCH_LABEL.get(r["arch"], r["arch"])
    bs = _bs(r)
    if bs is None:
        return name
    return f"{name} ($bs{{=}}{bs}$)"


def _sort_rows(rows: list[dict]) -> list[dict]:
    """Sort by ARCH_ORDER, then bs ascending."""
    def key(r):
        try:
            i = ARCH_ORDER.index(r["arch"])
        except ValueError:
            i = len(ARCH_ORDER)
        return (i, _bs(r) or 0)
    return sorted(rows, key=key)


def write_pr_auc_table_body(rows: list[dict], out_path: Path) -> None:
    """Body for the 12-column PR-AUC + ROC-AUC table at every S in S_GRID.
    Caller's tex file owns \\begin{table}, \\caption, \\label, and the
    column header row; this function emits only the body lines."""
    lines = ["% AUTO-GENERATED by scripts/c7_tex_snippets.py — do not edit.",
             "% Re-run the c7_paper_loop to refresh."]
    for r in _sort_rows(rows):
        m = r["metrics"]
        cells = [_row_label(r)]
        for S in S_GRID:
            cells.append(_fmt(m.get(f"pr_auc_S{S}")))
        for S in S_GRID:
            cells.append(_fmt(m.get(f"roc_auc_S{S}")))
        lines.append(" & ".join(cells) + r" \\")
    out_path.write_text("\n".join(lines) + "\n")


def write_headline_table_body(rows: list[dict], out_path: Path) -> None:
    lines = ["% AUTO-GENERATED by scripts/c7_tex_snippets.py — do not edit."]
    for r in _sort_rows(rows):
        m = r["metrics"]
        peak_mag = m.get("delta_gc_peak_magnitude")
        cells = [
            _row_label(r),
            _fmt(m.get("gc_at_peak_mag"), prec=2),
            _fmt(m.get("gc_at_baseline"), prec=2),
            _fmt(m.get("delta_gc_peak"), prec=3),
            f"${peak_mag:+g}$" if peak_mag is not None else r"\texttt{[TBD]}",
            _fmt(m.get("pr_auc_S8")),
            _fmt(m.get("roc_auc_S8")),
        ]
        lines.append(" & ".join(cells) + r" \\")
    out_path.write_text("\n".join(lines) + "\n")


def _peak_row(rows: list[dict], metric: str, *, higher_is_better=True) -> dict | None:
    valid = [r for r in rows if r["metrics"].get(metric) is not None]
    if not valid:
        return None
    return max(valid, key=lambda r: r["metrics"][metric] if higher_is_better
               else -r["metrics"][metric])


def write_results_macros(rows: list[dict], out_path: Path) -> None:
    """\\newcommand-style macros that the Results paragraph in main.tex
    can interpolate. Use \\providecommand so the .tex still typesets if
    a macro is missing (e.g. when a cell hasn't landed yet)."""
    lines = [
        "% AUTO-GENERATED by scripts/c7_tex_snippets.py — do not edit.",
        "% Use \\providecommand throughout so missing-cell builds don't fail.",
    ]

    n_cells = len(rows)
    archs_present = {r["arch"] for r in rows}
    # tfa dropped 2026-05-06 (post pod-crash budget cut); 7 cells expected.
    archs_expected = set(ARCH_ORDER) - {"stacked_sae", "tfa"}
    is_complete = archs_expected.issubset(archs_present) and n_cells >= 7

    lines.append(f"\\providecommand{{\\cseveennCells}}{{{n_cells}}}")
    lines.append(f"\\providecommand{{\\cseveennPending}}{{{7 - n_cells if n_cells < 7 else 0}}}")

    # Headline gc_at_peak winner
    top = _peak_row(rows, "gc_at_peak_mag")
    if top:
        m = top["metrics"]
        lines.append(f"\\providecommand{{\\cseveenTopGcCell}}{{{_row_label(top)}}}")
        lines.append(f"\\providecommand{{\\cseveenTopGcPeak}}{{{m['gc_at_peak_mag']:.2f}}}")
        lines.append(f"\\providecommand{{\\cseveenTopGcBaseline}}{{{m.get('gc_at_baseline', 0):.2f}}}")
        lines.append(f"\\providecommand{{\\cseveenTopGcPeakMag}}{{{m['delta_gc_peak_magnitude']:+g}}}")
        lift = m["gc_at_peak_mag"] - m.get("gc_at_baseline", 0)
        rel = (lift / m["gc_at_baseline"] * 100) if m.get("gc_at_baseline", 0) else 0
        lines.append(f"\\providecommand{{\\cseveenTopGcLift}}{{{lift:+.2f}}}")
        lines.append(f"\\providecommand{{\\cseveenTopGcRelLift}}{{{rel:+.0f}\\%}}")

    # Headline Δgc_peak winner
    top = _peak_row(rows, "delta_gc_peak")
    if top:
        m = top["metrics"]
        lines.append(f"\\providecommand{{\\cseveenTopDeltaCell}}{{{_row_label(top)}}}")
        lines.append(f"\\providecommand{{\\cseveenTopDelta}}{{{m['delta_gc_peak']:.3f}}}")

    # Headline PR-AUC@8 winner
    top = _peak_row(rows, "pr_auc_S8")
    if top:
        m = top["metrics"]
        lines.append(f"\\providecommand{{\\cseveenTopPrAucCell}}{{{_row_label(top)}}}")
        lines.append(f"\\providecommand{{\\cseveenTopPrAuc}}{{{m['pr_auc_S8']:.3f}}}")

    # Headline ROC-AUC@8 winner
    top = _peak_row(rows, "roc_auc_S8")
    if top:
        m = top["metrics"]
        lines.append(f"\\providecommand{{\\cseveenTopRocAucCell}}{{{_row_label(top)}}}")
        lines.append(f"\\providecommand{{\\cseveenTopRocAuc}}{{{m['roc_auc_S8']:.3f}}}")

    lines.append(f"\\providecommand{{\\cseveenComplete}}{{{int(is_complete)}}}")
    out_path.write_text("\n".join(lines) + "\n")


def main(*, output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    rows = load_canonical()
    if not rows:
        print("[c7_tex_snippets] no canonical c7 rows yet")
        return
    write_pr_auc_table_body(rows, output_dir / "c7_pr_auc_table.tex")
    write_headline_table_body(rows, output_dir / "c7_headline_table.tex")
    write_results_macros(rows, output_dir / "c7_results_macros.tex")
    print(f"[c7_tex_snippets] wrote 3 snippets covering {len(rows)} cells → {output_dir}")


def _purified_root() -> Path:
    return Path(__file__).resolve().parent.parent


def cli():
    root = _purified_root()
    ap = argparse.ArgumentParser(description=(
        "C7 LaTeX-snippet generator. Reads in-repo leaderboard."
    ))
    ap.add_argument(
        "--output-dir", type=Path,
        default=root / "figs" / "c7",
        help="Output directory (default: purified/figs/c7/).",
    )
    args = ap.parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    main(output_dir=args.output_dir)


if __name__ == "__main__":
    os.environ.setdefault("TQDM_DISABLE", "1")
    cli()
