#!/usr/bin/env bash
# Poll results/leaderboard.jsonl every 5 minutes; on any change to
# c1/c2 rows, re-render the synthetic paper bundles (markdown +
# plots) and push to origin/final-aniket.
#
# Outputs land in /workspace/aniket/temp_xc_paper at
# purified/docs/components/c{1,2}_paper_results.md (+ _assets/).
#
# Usage:
#   set -a; source /workspace/aniket/temp_xc/.env; set +a
#   cd /workspace/aniket/temp_xc-final/purified
#   nohup bash scripts/synthetic_paper_loop.sh \
#       > logs/synthetic_paper_loop.log 2>&1 &
#   echo $! > logs/synthetic_paper_loop.pid

set -u

SOURCE_PURIFIED=/workspace/aniket/temp_xc-final/purified
PAPER_WT=/workspace/aniket/temp_xc_paper
PAPER_PURIFIED="$PAPER_WT/purified"
OUTPUT_DIR="$PAPER_PURIFIED/docs/components"
LB="$SOURCE_PURIFIED/results/leaderboard.jsonl"
GH_TOKEN=${GH_TOKEN:-}

cd "$SOURCE_PURIFIED"
log() { printf "[%s] %s\n" "$(date -u +%H:%M:%S)" "$*"; }

# Hash only the c1/c2 _full_suite rows so we don't re-render when
# unrelated leaderboard rows (c3..c7) land.
sig() {
    [ -f "$LB" ] || { echo ""; return; }
    .venv/bin/python -c "
import json, hashlib, sys
h = hashlib.md5()
try:
    for line in open('$LB'):
        line = line.strip()
        if not line: continue
        try: r = json.loads(line)
        except: continue
        if r.get('component') not in ('c1','c2'): continue
        if not r.get('eval_cfg',{}).get('_full_suite'): continue
        h.update(line.encode())
    print(h.hexdigest())
except Exception:
    print('')
" 2>/dev/null
}

count_rows() {
    .venv/bin/python -c "
import json
n1 = n2 = 0
try:
    for l in open('$LB'):
        l = l.strip()
        if not l: continue
        try: r = json.loads(l)
        except: continue
        if not r.get('eval_cfg',{}).get('_full_suite'): continue
        if r.get('component')=='c1': n1 += 1
        elif r.get('component')=='c2': n2 += 1
except: pass
print(f'{n1},{n2}')
" 2>/dev/null
}

push_paper() {
    cd "$PAPER_WT"
    git add purified/docs/components/c1_paper_results.md \
            purified/docs/components/c1_paper_assets \
            purified/docs/components/c2_paper_results.md \
            purified/docs/components/c2_paper_assets 2>/dev/null
    if git diff --cached --quiet; then
        log "no diff to commit"
        cd "$SOURCE_PURIFIED"
        return 0
    fi
    local counts c1 c2
    counts=$(count_rows)
    c1=${counts%,*}
    c2=${counts#*,}
    local commit_msg
    commit_msg="c1+c2 paper auto: refresh synthetic bundles (c1=$c1, c2=$c2 leaderboard rows)

Auto-generated by purified/scripts/synthetic_paper_renderer.py.
Inputs: results/leaderboard.jsonl filtered to component in (c1,c2)
with eval_cfg._full_suite=true (the c{1,2}_synthetic_*_full driver flag).

Co-Authored-By: Claude Opus 4.7 (1M context) <noreply@anthropic.com>"
    git -c user.email="aniketdeshh@gmail.com" -c user.name="aniket" \
        commit -m "$commit_msg" >/dev/null
    log "committed $(git rev-parse --short HEAD)"
    if [ -z "$GH_TOKEN" ]; then
        log "WARNING: GH_TOKEN unset — local commit only"
        cd "$SOURCE_PURIFIED"
        return 0
    fi
    git fetch origin final-aniket 2>&1 | tail -1
    if ! git -c user.email="aniketdeshh@gmail.com" -c user.name="aniket" \
            rebase origin/final-aniket 2>&1 | tail -1; then
        log "rebase failed — aborting"
        git rebase --abort 2>/dev/null
        cd "$SOURCE_PURIFIED"
        return 1
    fi
    log "pushing"
    GIT_TERMINAL_PROMPT=0 \
    git -c "credential.helper=!f() { echo username=x-access-token; echo password=$GH_TOKEN; }; f" \
        push origin HEAD:final-aniket 2>&1 | tail -3
    cd "$SOURCE_PURIFIED"
}

last_sig=""
log "loop started — polling every 300s"

while true; do
    cur=$(sig)
    if [ -n "$cur" ] && [ "$cur" != "$last_sig" ]; then
        log "input signature changed → render"
        if .venv/bin/python -m scripts.synthetic_paper_renderer \
                --output-dir "$OUTPUT_DIR" 2>&1 | sed 's/^/  /'; then
            push_paper
            last_sig=$cur
        else
            log "renderer FAILED — will retry next tick"
        fi
    fi
    sleep 300
done
